### ISSUE TITLE
Database create fails

### ISSUE THREAD

**Issue by trickidicki** [uwi-info3180/flask-sqlite#1]
Running through the 'getting started' instructions and the database create stage fails (Windows Python 3.6 Virtualenv)

`>>> from app import db`

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\work\python\NPP_demo\app\__init__.py", line 14, in <module>
    from app import views
  File "C:\work\python\NPP_demo\app\views.py", line 10, in <module>
    from forms import UserForm
ModuleNotFoundError: No module named 'forms'
```

**Comment by trickidicki** [comment]
I managed to get it working by changing the import statements in `views.py`:

```
from app.forms import UserForm
from app.models import User
```

Hope that helps!

**Comment by ylynfatt** [comment]
If you submit a pull request, I'll merge in the change.

**Comment by ylynfatt** [comment]
@trickidicki this has now been resolved.
